# Generated by Django 5.1.7 on 2025-04-01 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_bbox', models.JSONField(null=True)),
                ('player_bbox', models.JSONField(null=True)),
                ('keypoints', models.JSONField(null=True)),
                ('result_image', models.ImageField(null=True, upload_to='results/')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='detector.uploadedimage')),
            ],
        ),
    ]
